# Generated by Django 2.0.3 on 2018-04-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180414_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titleimg',
            field=models.ImageField(blank=True, null=True, upload_to='titleimg/%Y/%m/%d/'),
        ),
    ]
